apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-env
namePrefix: prd-
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: nginx-web
  options:
    allowNameChange: true
images:
- name: nginx
  newTag: 1.26.2
configMapGenerator:
- name: nginx-configmap
  behavior: replace
  files:
    - index.html
resources:
- ../../base
