---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-server
  name: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: registry.redhat.io/rhel9/mysql-80@sha256:854905b75e5cfcb6f55fa53fb32c393ca34de1999d7714b026a53cff8b0694b2
          imagePullPolicy: IfNotPresent
          name: mysql-server
      imagePullSecrets:
        - name: 13421688-redhat-registry-pull-secret
