---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-mysql
  name: wp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-mysql
  template:
    metadata:
      labels:
        app: wp-mysql
    spec:
      containers:
        - image: registry.redhat.io/rhel9/mysql-80
          imagePullPolicy: Always
          name: wp-mysql
     imagePullSecrets:
        - name: 13421688-redhat-registry-pull-secret

