---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-server
  name: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: mysql-80
          imagePullPolicy: Always
          name: mysql-server
      imagePullSecrets:
        - name: 13421688-redhat-registry-pull-secret
