---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-server
  name: wp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-server
  template:
    metadata:
      labels:
        app: wp-server
    spec:
      containers:
        - image: quay.io/dsantosmt/wordpress:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
          - name: WORDPRESS_DB_HOST
            value: 192.168.0.69
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: WORDPRESS_DB_USER
            value: wordpress
          name: wp-server
      imagePullSecrets:
        - name: quay-credentials
