apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-server
  name: wp-web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-server
  type: LoadBalancer
