---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-web
  name: wp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-web
  template:
    metadata:
      labels:
        app: wp-web
    spec:
      containers:
        - image: quay.io/dsantosmt/wordpress:v1
        imagePullPolicy: Always
        name: wp-web
